%% SanityCheck.m
% function to check whether the LU decomp is implemented right
% simply by comparing results generated by
% official blackslash solve and my method

function[] = SanityCheck(n)
%%  
% n = 10:2:20;
    err = 0;
    for i = 1:length(n)
        A = rand(n(i), n(i));
        b = rand(n(i), 1);

        x1 = A\b;
        x2 = LuDecom(A, b, n(i), 0.001);

        err = err + norm(x1 - x2) / n(i);
    end

    fprintf('Difference between intrinsic and our method is %0.5f \n', err / length(n));

end